# Netlify configuration file

[build]
  # Directory to publish (relative to root of the repository)
  publish = "dist"
  
  # Build command
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  ROLLUP_NATIVE = "false"
  NODE_OPTIONS = "--max_old_space_size=4096"

# Handle SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 